### ISSUE TITLE
✨ Add the voting portal URL in the Election Event Dashboard page

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1024]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

As Admin user,
When 
I create a new election event
Then
The system should show the voting portal URL for that election Event on the Dashboard page of the Election Event

### Possible Implementation

-

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Can we get a design for how this should look?

**Comment by edulix** [comment]
Already implemented
