### ISSUE TITLE
✨ Voting Portal Login Language kept after login in 

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1025]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

As a Voter
When
I access the login page (Keycloak)
and I select a language available and fill in the credentials and click the login button
Then
I want  the voting portal to display in the language selected on the login page (Keycloak)

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
already implemented
