### ISSUE TITLE
🐞 Selecting a list doesn't show all list candidates

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1028]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Selecting a list doesn't show all list candidates in the review screen:

<img width="1145" alt="Screenshot 2024-05-31 at 06 59 14" src="https://github.com/sequentech/meta/assets/3913223/511fe70f-ba2c-4857-a1c6-ab6309bfb163">

### Expected Behavior

Selecting a list should show all list candidates in the review screen. Also you shouldn't be able to select both a list and a candidate in the list.

### Steps To Reproduce

1. In the Admin Portal, click in `New Election` in the sidebar, then click in `Create Election`.
2. Click in `Actions` button and then click in `Edit JSON` in the popup moenu and paste the following election configuration json into the modal dialog and accept: `<insert election-config.json here>`.
3. Then click in `Actions` button and then click in `Live preview` to open the voting booth.
4. In the start screen, the error appears as highlighted in red in the screenshot below: `<insert-screenshot-here>`.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Closing this, it has already been solved in #1020
