### ISSUE TITLE
✨ Tree structure for areas

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1040]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The system needs to allow the creation of a tree structure for areas, with the following implications
- voters can be assigned to each level of the tree
- voter will only see the question/contest in the voting portal of the area assigned and the higher levels
- The admin can decide to which level of the area tree he wants the resulting breakdown
- Area level on tally sheet

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
dupe of #1063
