### ISSUE TITLE
✨ Voter Authentication with only OTP

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1042]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

As a voter I want to be able to authenticate in the system only using OTP
When
I access the login screen of the form will only request the username
The voter will have to fill the username field and click the login button
Then
the system will send an SMS and/or email with an OTP to the voter 
the system will show a form to input the OTP
Once the OTP is successfully filled in the Form the voter will have access to the ballot

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
@lnabergoi you can actually use the "Username Form" authenticator step, it already exist:
<img width="1420" alt="image" src="https://github.com/sequentech/meta/assets/81968/5df212ee-1f4a-46cd-8c9f-5ad5efb0ff0d">

<img width="1420" alt="image" src="https://github.com/sequentech/meta/assets/81968/bdfd18f9-ac79-4979-a801-c8f69c119b13">

<img width="739" alt="image" src="https://github.com/sequentech/meta/assets/81968/e4ece70f-f812-4c27-b81b-3161df681938">
