### ISSUE TITLE
🐞 Admin Portal - Tally List - Trustee column empty

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1099]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

List of tallys should show an empty value for the trustee column:
<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/28b7da58-587f-409e-a120-e42509aec3e9">

### Expected Behavior

Trustees should be shown by their name as badges, in a similar manner as Contests are shown in Area list:
<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/0b2d5f44-847e-4d6b-9caf-ca6cc7714eab">

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/520
```

**Comment by yvwbimpong** [comment]
![Image](https://github.com/sequentech/meta/assets/29688503/5df6911d-ffa9-4d07-a3d3-d6269e4c532c)

**Comment by yvwbimpong** [comment]
![Image](https://github.com/sequentech/meta/assets/29688503/a6239b10-17fa-48e6-ba38-5dd0c4e502a5)
