### ISSUE TITLE
🐞 Admin Portal - Tally - Selecting only one Election to Tally shows all elections as being tallied

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1132]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Selecting only one Election to Tally still launches all elections to tally.

Selection screen (Start Step in the wizard):
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/bb5c7a8a-26f7-4cc5-8b24-23e090b55b36">

Resulted elections being tallied (Ceremony Stepin the wizard):
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/1f586e27-efaf-4b11-b1ad-5573afced9cf">

But then during the actually tally, after ceremony has been executed, only the selected Elections are being tallied:
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/78dcdfb4-6a7c-4542-a0f5-33bd0f1cf41b">

Also, in the moment between switching between Start Step and Ceremony Step, the `Start Ceremony >` button gets disabled while waiting, but the checkboxes of the elections don't get disabled.

You can check importing the following election event: 
[export-election-event-d6f7fb00-ba29-46da-af1b-12194ef027f1.json](https://github.com/user-attachments/files/15862037/export-election-event-d6f7fb00-ba29-46da-af1b-12194ef027f1.json)

### Expected Behavior

It should only and consistently show the selected election(s) to be tallied.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/512
```

**Comment by xalsina-sequent** [comment]
I've added a filter on the TallyElectionsList so it filters out the elections that were not selected in the creation step as well as making sure the list is disabled after clicking the start button.
