### ISSUE TITLE
✨ candidate images in simultaneous-questions layout

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#123]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We would like to use ballot papers with candidate images, we need parameters to transfer the image URL. There is no support of images in the simultaneous-questions layout

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
This is already supported, as discussed yesterday with Sergiy. Closing, please feel free to reopen if need be.
