### ISSUE TITLE
🐞 ualicante environment not working

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1231]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

After logging into the [admin-portal](https://admin-portal-ualicante.sequent.vote) on keycloak, it tries to return to the admin-portal but I face a whitescreen instead.

![image](https://github.com/sequentech/meta/assets/168065560/ae6baba5-5b7f-4da1-bda4-81391f465a2f)

### Expected Behavior

I expect this environment/installation to run properly

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
closing unless someone says this is still happening
