### ISSUE TITLE
🐞 btn. continue has no ng-i18next tag

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#140]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Just this button text has no ng-i18next tag
![image](https://github.com/sequentech/meta/assets/87812708/e1f37c16-dfa2-4451-83a1-64df31963085)

### Expected Behavior

Would be cool if this tag appears

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
I agree it would be cool, but this is not a bug. It's a internationalized string, and it's not a requirement that it appears there and depends on multiple factors. By default it's `avBooth.continueButton`.
