### ISSUE TITLE
🐞 Can't import voters without email

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1405]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

When importing voters, if the csv doesn't have an email field, the import fails [here](https://github.com/sequentech/step/blob/6c82e25795b41628c918da5d47c9667c8e84113a/packages/windmill/src/tasks/import_users.rs#L624).

```
    0: db error: ERROR: column "email" does not exist
       HINT: There is a column named "email" in table "user_entity", but it cannot be referenced from this part of the query.
```

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Fixed by #1611
