### ISSUE TITLE
🐞 tally tar gz folder is a hidden folder

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1469]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

tally tar gz folder is a hidden folder

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/588
```

**Comment by edulix** [comment]
@Findeton I understand what this does, but I don't understand why this is a problem? what kind of problem does this solve? Why is it a problem the fact that the tally.tar.gz is a hidden folder?
