### ISSUE TITLE
✨ Tally:  replace Hasura with Postgres queries

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1492]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Tally:  replace Hasura with Postgres queries

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
dupe of #982
