### ISSUE TITLE
✨ Verifier deployment

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#157]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement deployment system for the new-ballot-verifier using kubernetes.

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] Task 1
```

**Comment by edulix** [comment]
Done in #87
