### ISSUE TITLE
✨ Fix github actions

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#160]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Make github actions pass.

### Possible Implementation

-

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

### Additional context

-

**Comment by edulix** [comment]
done
