### ISSUE TITLE
✨ Add voting-portal documentation

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#161]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add documentation.

### Possible Implementation

-

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

### Additional context

-

**Comment by edulix** [comment]
Documentation will be done more generally
