### ISSUE TITLE
✨ Switch to using 2nd-gen endpoints/data

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#166]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Switch to using 2nd-gen endpoints/data.

### Possible Implementation

-

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

### Additional context

-

**Comment by edulix** [comment]
Now this has been moved to https://github.com/sequentech/meta/issues/173
