### ISSUE TITLE
✨ Election Internationalization support

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#169]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support election-specific translations, and add translations for more languages.

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by markgrafd** [comment]
We would also be very interested in this function. Especially the definition of locales only in the deployment process is actually very challenging. We need a way to use different languages via JSON configuration in single elections. The language selection in the voting booth should also be disabled/hidden when using only one language. It should also be possible to define the order of the language displayed in the selection menu by the order of the parameters within the JSON file.

**Comment by edulix** [comment]
done
