### ISSUE TITLE
✨ Add error checks on voting/review screen

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#172]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add error checks on voting/review screen

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Duplicate of #237
