### ISSUE TITLE
✨ Review sequent-core encryption

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#180]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Review sequent-core encryption, at least `encrypt_plaintext_answer` and  `recreate_encrypt_answer`. https://github.com/sequentech/sequent-core/blob/main/src/encrypt.rs 

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by ruescasd** [comment]
Ok, but a better way to do this is needed:

https://github.com/sequentech/sequent-core/blob/main/src/encrypt.rs#L149
