### ISSUE TITLE
Signatures and certificates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#257]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Determine signature and certificate use cases.\
Determine signature key and certificate formats.\
Add required implementations to strand.

### Identified tasks

```[tasklist]
- [x] Revocation scenarios
- [x] Reading openssl formats (test reading certificate x509, spki pk, pkcs8 sk)
- [x] Extracting pk from certificate
- [x] Verifying certificate signatures
- [x] Creating certificate signing request from strand pk (when sk/pk generated on browser)
- [x] Signing certificate signing request with openssl generated ca
```

### Notes

CRL's will not be used in the short term.

The proposed CA structure is 2-levels deep, Root + deployment

All certificates will be generated statically, except for voter certificates.

**Comment by ruescasd** [comment]
See also https://github.com/sequentech/backend-services/wiki/Notes-on-signatures-and-certificates
