### ISSUE TITLE
✨ Split sequent-core wasm methods

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#271]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

There are some methods included in the `sequent-core` wasm project that are only used in the `ballot-verifier`. These need to either be feature-gated or moved into a separate `ballot-verifier` package, to avoid creating a large wasm package binary.

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
unneeded, maybe use feature flags in the future but not doing this now
