### ISSUE TITLE
✨ Export/refactor code to check implicit invalid votes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#298]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

In `sequent-core` implicitly invalid ballots are already checked. However that code is not readily accesible. Refactor the code to expose it so that for example `velvet` can use it.

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
already done
