### ISSUE TITLE
✨ Only insert last cast_vote from each user

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#316]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Only insert last cast_vote from each user

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
done recently by @Findeton
