### ISSUE TITLE
✨ Handle election status before election tally

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#317]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Depending on the election event configuration, doing the tally should be possible or not, for example if the elections are stopped or if it's allowed to do recurrent tallies before the election is tallied.

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
already handled as we want
