### ISSUE TITLE
✨ Keycloak initialization configuration/script

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#338]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It should be possible to configure the super-admin role for Keycloak from environment variables. Reading these variables a script should create the reign if it doesn't exist, set the default admin user(s)/password(s) and permissions/roles (roles/groups in keycloak).

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
it's done
