### ISSUE TITLE
🐞 Braid fails to build. Session: parameter may not live long enough

### ISSUE THREAD

**Issue by ruescasd** [sequentech/meta#415]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

error[E0310]: the parameter type `C` may not live long enough

### Expected Behavior

-

### Steps To Reproduce

Use

RUN rustup default nightly

in braid dockerfile

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
It seems to be working now? https://github.com/sequentech/backend-services/actions/runs/7187625576/job/19575590509
