### ISSUE TITLE
🐞 Remove create if not exist from s3 code 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#479]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

When s3 module tries to look for the bucket if it doesn't find it, it will call the method "create if not exist" to create a new s3 bucket. 
This can be problematic for few reasons: 
1. We don't know the bucket was created
2. It is not in the "source of truth" 
3. It might be trying to create in a wrong account / section 

### Expected Behavior

Fail with an error that the bucket does not exist 

### Steps To Reproduce

1. In the Admin Portal, click in `New Election` in the sidebar, then click in `Create Election`.
2. Click in `Actions` button and then click in `Edit JSON` in the popup moenu and paste the following election configuration json into the modal dialog and accept: `<insert election-config.json here>`.
3. Then click in `Actions` button and then click in `Live preview` to open the voting booth.
4. In the start screen, the error appears as highlighted in red in the screenshot below: `<insert-screenshot-here>`.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
This has already been done
