### ISSUE TITLE
🐞 Some invalid ballots not counted as invalid in Tally

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#508]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

In the tally, some ballots are invalid but they are being dismissed rather than being counted as invalid.

### Expected Behavior

Count all invalid ballots.

### Steps To Reproduce

-

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/391
```

**Comment by edulix** [comment]
This was fixed in https://github.com/sequentech/meta/issues/868
