### ISSUE TITLE
🐞 Ballot-verifier: order contests by creation date/custom order

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#539]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

The voting portal (should) order contests by creation date. This sort method should be moved to ui-essentials and it should be used also in the ballot verifier to order the options the same way as in the voting portal.

This issue is related to [this PR.](https://github.com/sequentech/backend-services/pull/322)

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Closing this ticket, continuing in https://github.com/sequentech/meta/issues/1023
