### ISSUE TITLE
🐞 Can't enable language in admin-portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#560]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Languages/translations can't be enabled in the admin portal.

### Expected Behavior

Active languages are being stored in the root of the tenant settings, and then they're don't seem to be used in the lang selection in the header.

Change the settings to store the active langs inside a specific key, and change the header to support reading it.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Felix already did it
