### ISSUE TITLE
✨ Add trustees config to admin portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#576]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add trustees config to admin portal. There are components already for configuring trustees but they're not accessible, they're not translated and they don't manage the empty state.

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Done in #527
