### ISSUE TITLE
✨ Election Templates

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#850]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

-

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
we support export and import so I guess this should be it
